_wandb:
    value:
        cli_version: 0.25.1
        e:
            auii7bqt81zuo36p28ty5n1fj1imdcpi:
                args:
                    - --stage
                    - model_training
                    - --config
                    - config/config.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "214747312128"
                        used: "20043730944"
                email: errorprajapati@gmail.com
                executable: C:\Users\Aryan\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: c67b51f4eeb030c74493c3b290c0dad64c841927
                    remote: https://github.com/Jitu9427/salary-prediction.git
                host: INBOOK_Y2_PLUS
                memory:
                    total: "16909541376"
                os: Windows-11-10.0.26200-SP0
                program: D:\mlops\salary prediction\main.py
                python: CPython 3.13.5
                root: D:\mlops\salary prediction
                startedAt: "2026-03-14T06:15:51.533215Z"
                writerId: auii7bqt81zuo36p28ty5n1fj1imdcpi
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.25.1
            "8":
                - 2
                - 3
            "12": 0.25.1
            "13": windows-amd64
base_models:
    value:
        gradient_boosting:
            learning_rate: 0.05
            max_depth: 6
            n_estimators: 300
            random_state: 42
            subsample: 0.8
        random_forest:
            max_depth: 15
            min_samples_leaf: 2
            min_samples_split: 5
            n_estimators: 300
            n_jobs: -1
            random_state: 42
        ridge:
            alpha: 10
evaluation:
    value:
        max_rmse: 30000
        min_r2: 0.75
meta_learner:
    value:
        alpha: 1
        cv_folds: 5
        model: ridge
preprocessing:
    value:
        outlier_method: iqr
        outlier_threshold: 1.5
        target_col: salary_in_usd
